import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import en from '../locales/en';
import fr from '../locales/fr';

export default function Home() {
	const router = useRouter();
	const { locale } = router;
	const texts = locale === 'en' ? en : fr;

	return (
		<>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1>{texts.boardTile}</h1>
				<p>{texts.description}</p>
				<Image src="https://i.dummyjson.com/data/products/1/1.jpg" alt={texts.heroAlt} width={500} height={300} />
			</main>
		</>
	)
}
